apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-webapp1
  name: nginx-webapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-webapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-webapp1
    spec:
      containers:
      - image: vishwa787/webapp-1
        name: webapp-1
        resources: {}
status: {}
