apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-webapp1-service
  name: nginx-webapp1-service
spec:
  ports:
  - name: 5678-80
    port: 5678
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-webapp1
  type: NodePort
status:
  loadBalancer: {}
